#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID

handle_exit() {
	sudo rm -rf "/var/run/myscript.pid"
	exit 0
}

trap "echo I hate the kill command;handle_exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "handle_sigterm" SIGQUIT

sudo sh -c "echo $$ >> /var/run/myscript.pid"
while true; do
    echo "To infinity and beyond"
    sleep 1
done
