#!/usr/bin/env bash
# An init script for the manage_my_process script
start_service(){
	./manage_my_process &
	echo $! > /var/run/my_process.pid
}

stop_service(){
	if [ -f /var/run/my_process.pid ]; then
		kill "$(pgrep -f /manage_my_process)"
		rm "/var/run/my_process.pid"
	fi
}

restart_service(){
	if [ -f /var/run/my_process.pid ]; then
		kill "$(pgrep -f /manage_my_process)"
		rm "/var/run/my_process.pid"
	fi
	./manage_my_process &
	echo $! > /var/run/my_process.pid
}

case "$1" in
	start)
		start_service
		echo "manage_my_process started"
	;;
	stop)
		stop_service
		echo "manage_my_process stopped"
	;;
	restart)
		restart_service
		echo "manage_my_process restarted"
	;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
exit 0
