#!/usr/bin/env bash
# Displays number from 1 to 100 with the exception that if a number is div by 5 or 3 or both
i=1
for i in {1..100}; do
	if [ $((i % 5)) == 0 ] && [ $((i % 3)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) == 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) == 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi
done
